name: Sync Craft TextBundle

on:
  push:
    branches: [ main ]
    paths:
      - 'content/ai-scale.textbundle/**'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare output
        run: mkdir -p docs

      - name: Copy TextBundle content
        run: |
          if [ -f content/ai-scale.textbundle/text.markdown ]; then
            cp content/ai-scale.textbundle/text.markdown docs/ai-scale.md
          elif [ -f content/ai-scale.textbundle/text.html ]; then
            cp content/ai-scale.textbundle/text.html docs/ai-scale.html
          else
            echo "No text.markdown or text.html found in TextBundle."
            exit 1
          fi

      - name: Rewrite asset paths in Markdown (if needed)
        if: hashFiles('docs/ai-scale.md') != ''
        run: |
          # If Craft wrote image links like: ![](assets/xyz.png)
          # rewrite them to the repo path: content/ai-scale.textbundle/assets/xyz.png
          sed -E 's@\]\((assets/[^)]+)\)@]\(content/ai-scale.textbundle/\1\)@g' -i docs/ai-scale.md

      - name: Generate README.md
        run: |
          OUT="README.md"
          {
            # Only show the line if TS is non-empty
            TS="$(date -u +"%Y-%m-%d %H:%M:%S UTC")"
            if [ -n "$TS" ]; then
              echo "_Last synced (auto): $TS_"
              echo
            fi
            echo "---"
            echo
            if [ -f docs/ai-scale.md ]; then
              cat docs/ai-scale.md
            else
              cat docs/ai-scale.html
            fi
            echo
          } > "$OUT"

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add docs README.md
            git commit -m "chore(sync): update from Craft TextBundle"
            git push
          else
            echo "No changes to commit."
          fi
