name: Sync Craft TextBundle

on:
  push:
    branches: [ master ]
    paths:
      - 'content/ai-scale.textbundle/**'
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with LFS)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Prepare output folder
        run: mkdir -p docs

      - name: Copy TextBundle content
        run: |
          if [ -f content/ai-scale.textbundle/text.markdown ]; then
            cp content/ai-scale.textbundle/text.markdown docs/ai-scale.md
          elif [ -f content/ai-scale.textbundle/text.html ]; then
            cp content/ai-scale.textbundle/text.html docs/ai-scale.html
          else
            echo "No text.markdown or text.html found in TextBundle."
            exit 1
          fi

      - name: Rewrite asset paths in Markdown (if needed)
        if: hashFiles('docs/ai-scale.md') != ''
        run: |
          # Convert ![](assets/xyz.png) → !(content/ai-scale.textbundle/assets/xyz.png)
          sed -E 's@\]\((assets/[^)]+)\)@]\(content/ai-scale.textbundle/\1\)@g' -i docs/ai-scale.md

      - name: Generate README.md
        run: |
          TS="$(date -u +"%Y-%m-%d %H:%M:%S UTC")"
          OUT="README.md"
          {
            echo "> [!WARNING]"
            echo "> This synced copy may not be up to date."
            echo
            echo "> [!NOTE]"
            echo "> Views and interpretations here are my opinion only."
            echo
            if [ -n "$TS" ]; then
              echo "_Last synced (auto): $TS_"
              echo
            fi
            echo "---"
            echo
            if [ -f docs/ai-scale.md ]; then
              cat docs/ai-scale.md
            else
              cat docs/ai-scale.html
            fi
            echo
          } > "$OUT"

      - name: Commit changes (docs + README only)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain docs README.md)" ]; then
            git add docs README.md
            git commit -m "chore(sync): update README and docs from Craft TextBundle"
            git push
          else
            echo "No changes to commit."
          fi
